#!/usr/bin/env bash
# Copy this working tree into a Palworld install so the game runs what you just edited.
#
#   tools/deploy.sh                       # the default install below
#   tools/deploy.sh "/path/to/Palworld"   # somewhere else
#
# The mod folder is REPLACED, not merged: a file you deleted here has to disappear there too,
# or the game keeps loading it. deprecated/ and tmp/ are reference-only and are left behind.
#
# Lua is read at mod load, so a fresh deploy needs a game restart the first time. After that,
# deploy again and press F9 in game — the framework reloads without a restart.
set -euo pipefail

GAME="${1:-/mnt/e/SteamLibrary/steamapps/common/Palworld}"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$GAME/Pal/Binaries/Win64/ue4ss/Mods/PalForge"

[ -d "$SRC/Scripts/palforge" ] || { echo "not a PalForge tree: $SRC" >&2; exit 1; }
[ -d "$GAME/Pal/Binaries/Win64/ue4ss/Mods" ] || {
    echo "no UE4SS Mods directory under $GAME" >&2; exit 1; }

echo "source: $SRC/Scripts"
echo "target: $DEST/Scripts"

# STAGE, THEN SWAP. Deleting Scripts/ and re-copying leaves a window of a second or two in
# which the mod directory is incomplete, and pressing F9 during that window fails the reload
# with "module 'palforge.core.registry' not found" — which has happened, and which reads like a
# code error rather than a race. Everything is built alongside the live copy and moved into
# place with a rename, so the game never sees a half-populated tree.
STAGE="$DEST/.Scripts.staging"
OLD="$DEST/.Scripts.previous"
rm -rf "$STAGE" "$OLD"
mkdir -p "$STAGE"

# Everything the mod needs at runtime. tests/ stays: the kernel runs it at startup in dev.
cp -r "$SRC/Scripts/main.lua" "$STAGE/main.lua"
cp -r "$SRC/Scripts/palforge" "$STAGE/palforge"
rm -rf "$STAGE/palforge/deprecated" "$STAGE/palforge/tmp"

# A BUILD STAMP, so a stale run is obvious in the log instead of being diagnosed for an hour.
# Lua that is already loaded stays loaded: copying files here changes nothing in a running game
# until F9 (reload) or a restart. Every run of the suite prints this stamp, so if the log shows
# an older one than the deploy that just happened, F9 was not pressed and nothing in that log is
# evidence about the current code. This has cost a full debugging round more than once.
{
    echo '-- GENERATED by tools/deploy.sh. The suite prints this so a stale run is visible.'
    echo "return \"$(date '+%Y-%m-%d %H:%M:%S')\""
} > "$STAGE/palforge/build.lua"

# The swap. Two renames, so the only moment Scripts/ does not exist is between them.
[ -d "$DEST/Scripts" ] && mv "$DEST/Scripts" "$OLD"
mv "$STAGE" "$DEST/Scripts"
rm -rf "$OLD"

# UE4SS starts a mod only when this file is present.
: > "$DEST/enabled.txt"

files=$(find "$DEST/Scripts" -type f | wc -l)
echo "deployed $files file(s)"
echo
echo "keys once the game is running:"
echo "  F1  run the API test suite        F5  reflection probe"
echo "  F9  reload without restarting     F6/F7/F8  the other probes"
